// PackagesTable.tsx

import React, { useState, useMemo } from 'react';
import Modal from './Modal';

// Example interfaces (adjust as needed)
interface IPackage {
  docId: string;
  title?: string;
  slug?: string;
  description?: string;
  category?: string;
  image?: string;
  _salePrice?: number;
  collectionsDrinks?: string[];
  packages?: Array<{
    size?: number;
    roundUpOrDown?: number;
    discount?: number;
  }>;
  [key: string]: any; // For any other fields
}

interface IDrink {
  docId: string;
  name: string;
  [key: string]: any; // For any other fields
}

interface SortConfig {
  key: string | null;
  direction: 'ascending' | 'descending';
}

interface PackagesTableProps {
  packages: IPackage[];
  drinks: IDrink[];
  onPackageChange: (docId: string, path: string[], value: any) => void;
  onSavePackage: (pkg: IPackage) => void;
  onDeletePackage: (docId: string) => void;
  onAddPackage: (pkg: IPackage) => void;
}

const PackagesTable: React.FC<PackagesTableProps> = ({
  packages,
  drinks,
  onPackageChange,
  onSavePackage,
  onDeletePackage,
  onAddPackage,
}) => {
  const [editingRows, setEditingRows] = useState<Record<string, boolean>>({});
  const [modalType, setModalType] = useState<string | null>(null);
  const [currentPackage, setCurrentPackage] = useState<IPackage | null>(null);
  const [selectedDrinks, setSelectedDrinks] = useState<string[]>([]);
  const [newPackage, setNewPackage] = useState<IPackage>({} as IPackage);
  const [showAddModal, setShowAddModal] = useState<boolean>(false);

  // State for sorting
  const [sortConfig, setSortConfig] = useState<SortConfig>({
    key: null,
    direction: 'ascending',
  });

  const [packagesData, setPackagesData] = useState<
    Array<{ size?: number; roundUpOrDown?: number; discount?: number }>
  >([]);

  const toggleEditing = (docId: string) => {
    setEditingRows((prev) => ({
      ...prev,
      [docId]: !prev[docId],
    }));
  };

  // Define the desired column order
  const columnOrder = [
    'title',
    'slug',
    'description',
    'category',
    'image',
    '_salePrice', // Private field
    'collectionsDrinks',
    'packages',
  ];

  // Function to handle sorting
  const requestSort = (key: string) => {
    let direction: 'ascending' | 'descending' = 'ascending';
    if (sortConfig.key === key && sortConfig.direction === 'ascending') {
      direction = 'descending';
    }
    setSortConfig({ key, direction });
  };

  // Apply sorting to packages data
  const sortedPackages = useMemo(() => {
    let sortablePackages = [...packages];
    if (sortConfig.key !== null) {
      sortablePackages.sort((a, b) => {
        const aValue = a[sortConfig.key!];
        const bValue = b[sortConfig.key!];

        if (aValue === undefined || aValue === null) return 1;
        if (bValue === undefined || bValue === null) return -1;

        let order = 0;

        if (typeof aValue === 'number' && typeof bValue === 'number') {
          order = aValue - bValue;
        } else {
          order = aValue.toString().localeCompare(bValue.toString());
        }

        return sortConfig.direction === 'ascending' ? order : -order;
      });
    }
    return sortablePackages;
  }, [packages, sortConfig]);

  const handleCellClick = (pkg: IPackage, key: string) => {
    if (key === 'collectionsDrinks') {
      setCurrentPackage(pkg);
      const drinksArray = Array.isArray(pkg.collectionsDrinks)
        ? pkg.collectionsDrinks
        : [];
      setSelectedDrinks(drinksArray);
      setModalType('drinksSelection');
    } else if (key === 'packages') {
      // Handle editing nested packages array
      setCurrentPackage(pkg);
      setPackagesData(pkg.packages || []);
      setModalType('packagesEditing');
    }
  };

  const handleAddPackage = () => {
    setNewPackage({
      title: '',
      slug: '',
      description: '',
      category: '',
      image: '',
      _salePrice: 0,
      collectionsDrinks: [],
      packages: [],
      docId: '', // docId is typically generated by the DB, you can omit or handle differently
    });
    setShowAddModal(true);
  };

  const handleSaveNewPackage = () => {
    onAddPackage(newPackage);
    setShowAddModal(false);
    setNewPackage({} as IPackage);
  };

  // Function to update newPackage state
  const updateNewPackageField = (key: string, value: any) => {
    setNewPackage((prev) => ({
      ...prev,
      [key]: value,
    }));
  };

  // Function to update currentPackage state (for editing)
  const updateCurrentPackageField = (key: string, value: any) => {
    if (!currentPackage) return;
    const updatedPackage = { ...currentPackage };
    updatedPackage[key] = value;
    onPackageChange(currentPackage.docId, [key], value);
    setCurrentPackage(updatedPackage);
  };

  return (
    <div className="mb-8">
      <h2 className="text-2xl font-bold mb-4">Packages</h2>
      <button
        className="mb-4 bg-green-500 text-white px-4 py-2 rounded"
        onClick={handleAddPackage}
      >
        Add New Package
      </button>
      <div className="overflow-x-auto">
        <table className="min-w-full border-collapse">
          <thead className="sticky top-0 bg-white">
            <tr>
              <th className="border px-4 py-2">Edit</th>
              {columnOrder.map((key) => (
                <th
                  key={key}
                  className="border px-4 py-2 cursor-pointer"
                  onClick={() => requestSort(key)}
                >
                  {key.startsWith('_') ? key.substring(1) : key}
                  {sortConfig.key === key ? (
                    sortConfig.direction === 'ascending' ? ' 🔼' : ' 🔽'
                  ) : null}
                </th>
              ))}
              <th className="border px-4 py-2">Save</th>
              <th className="border px-4 py-2">Delete</th>
            </tr>
          </thead>
          <tbody>
            {sortedPackages.map((pkg) => {
              const isEditing = editingRows[pkg.docId] || false;
              return (
                <tr key={pkg.docId} className="border-b">
                  <td className="border px-4 py-2 text-center whitespace-nowrap">
                    <button
                      className="bg-blue-500 text-white px-2 py-1 rounded"
                      onClick={() => toggleEditing(pkg.docId)}
                    >
                      {isEditing ? 'Lock' : 'Edit'}
                    </button>
                  </td>
                  {columnOrder.map((key) => {
                    const value = pkg[key];
                    const isObject =
                      typeof value === 'object' && value !== null;
                    const isPrivate = key.startsWith('_');

                    // Adjust cell width based on content
                    const cellStyle = {
                      whiteSpace: 'nowrap' as const,
                      maxWidth: '200px',
                    };

                    if (key === 'image') {
                      return (
                        <td
                          key={key}
                          className={`border px-4 py-2 ${
                            isPrivate ? 'text-red-500' : ''
                          }`}
                          style={cellStyle}
                        >
                          <div className="flex flex-col items-center">
                            {typeof value === 'string' && value && (
                              <img
                                src={value}
                                alt="Package"
                                className="h-16 w-auto mb-2"
                              />
                            )}
                            {isEditing && (
                              <input
                                type="file"
                                accept="image/*"
                                onChange={(e) => {
                                  if (
                                    e.target.files &&
                                    e.target.files[0]
                                  ) {
                                    const file = e.target.files[0];
                                    onPackageChange(pkg.docId, [key], file);
                                  }
                                }}
                              />
                            )}
                          </div>
                        </td>
                      );
                    } else if (key === 'collectionsDrinks' || key === 'packages') {
                      return (
                        <td
                          key={key}
                          className={`border px-4 py-2 ${
                            isPrivate ? 'text-red-500' : ''
                          }`}
                          style={cellStyle}
                        >
                          <button
                            className="text-blue-500 underline"
                            onClick={() => handleCellClick(pkg, key)}
                          >
                            {key === 'collectionsDrinks'
                              ? 'Manage Drinks'
                              : 'Edit Packages'}
                          </button>
                        </td>
                      );
                    } else if (isObject) {
                      return (
                        <td
                          key={key}
                          className={`border px-4 py-2 ${
                            isPrivate ? 'text-red-500' : ''
                          }`}
                          style={cellStyle}
                        >
                          <span>{JSON.stringify(value)}</span>
                        </td>
                      );
                    } else {
                      return (
                        <td
                          key={key}
                          className={`border px-4 py-2 ${
                            isPrivate ? 'text-red-500' : ''
                          }`}
                          style={cellStyle}
                        >
                          <input
                            type="text"
                            value={value || ''}
                            onChange={(e) => {
                              let newValue: any;
                              if (e.target.type === 'number') {
                                newValue = e.target.valueAsNumber;
                              } else {
                                newValue = e.target.value;
                              }
                              onPackageChange(pkg.docId, [key], newValue);
                            }}
                            disabled={!isEditing || key === 'docId'}
                            className={`border p-1 w-full ${
                              isPrivate ? 'text-red-500' : ''
                            }`}
                          />
                        </td>
                      );
                    }
                  })}
                  <td className="border px-4 py-2 text-center whitespace-nowrap">
                    {isEditing && (
                      <button
                        className="bg-green-500 text-white px-2 py-1 rounded"
                        onClick={() => onSavePackage(pkg)}
                      >
                        Save
                      </button>
                    )}
                  </td>
                  <td className="border px-4 py-2 text-center whitespace-nowrap">
                    <button
                      className="bg-red-500 text-white px-2 py-1 rounded"
                      onClick={() => onDeletePackage(pkg.docId)}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Add New Package Modal */}
      {showAddModal && (
        <Modal
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          title="Add New Package"
        >
          <div className="space-y-4">
            {columnOrder.map((key) => {
              if (key === 'docId') return null;
              const value = newPackage[key];
              const isObject =
                typeof value === 'object' && value !== null;
              const isPrivate = key.startsWith('_');

              return (
                <div key={key}>
                  <label
                    className={`block text-sm font-medium ${
                      isPrivate ? 'text-red-500' : 'text-gray-700'
                    }`}
                  >
                    {key.startsWith('_') ? key.substring(1) : key}
                  </label>
                  {key === 'image' ? (
                    <div className="flex flex-col items-center">
                      {typeof value === 'string' && value && (
                        <img
                          src={value}
                          alt="Package"
                          className="h-16 w-auto mb-2"
                        />
                      )}
                      <input
                        type="file"
                        accept="image/*"
                        onChange={(e) => {
                          if (e.target.files && e.target.files[0]) {
                            const file = e.target.files[0];
                            updateNewPackageField(key, file);
                          }
                        }}
                      />
                    </div>
                  ) : key === 'collectionsDrinks' || key === 'packages' ? (
                    <button
                      className="text-blue-500 underline"
                      onClick={() => {
                        setCurrentPackage(newPackage);
                        if (key === 'collectionsDrinks') {
                          setSelectedDrinks(
                            newPackage.collectionsDrinks || []
                          );
                          setModalType('drinksSelectionForNewPackage');
                        } else if (key === 'packages') {
                          setPackagesData(newPackage.packages || []);
                          setModalType('packagesEditingForNewPackage');
                        }
                      }}
                    >
                      {key === 'collectionsDrinks'
                        ? 'Manage Drinks'
                        : 'Edit Packages'}
                    </button>
                  ) : isObject ? (
                    <textarea
                      value={JSON.stringify(value, null, 2)}
                      onChange={(e) => {
                        try {
                          const parsedValue = JSON.parse(e.target.value);
                          updateNewPackageField(key, parsedValue);
                        } catch (error) {
                          console.error('Invalid JSON');
                        }
                      }}
                      className="border p-1 w-full"
                      rows={4}
                    />
                  ) : (
                    <input
                      type="text"
                      value={value || ''}
                      onChange={(e) => {
                        let val: any;
                        if (e.target.type === 'number') {
                          val = e.target.valueAsNumber;
                        } else {
                          val = e.target.value;
                        }
                        updateNewPackageField(key, val);
                      }}
                      className={`border p-1 w-full ${
                        isPrivate ? 'text-red-500' : ''
                      }`}
                    />
                  )}
                </div>
              );
            })}
            <div className="flex justify-end mt-4">
              <button
                onClick={handleSaveNewPackage}
                className="bg-green-500 text-white px-4 py-2 rounded mr-2"
              >
                Save
              </button>
              <button
                onClick={() => setShowAddModal(false)}
                className="bg-gray-300 px-4 py-2 rounded"
              >
                Cancel
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* Drinks Selection Modal */}
      {(modalType === 'drinksSelection' ||
        modalType === 'drinksSelectionForNewPackage') && (
        <Modal
          isOpen={true}
          onClose={() => {
            setModalType(null);
            setSelectedDrinks([]);
          }}
          title="Select Drinks"
        >
          <div className="flex">
            <div className="w-1/2">
              <h3 className="text-lg font-bold mb-2">Available Drinks</h3>
              <div className="border h-64 overflow-y-scroll">
                <ul>
                  {drinks
                    .filter((drink) => !selectedDrinks.includes(drink.docId))
                    .map((drink) => (
                      <li
                        key={drink.docId}
                        onDoubleClick={() => {
                          setSelectedDrinks([
                            ...selectedDrinks,
                            drink.docId,
                          ]);
                        }}
                        className="p-2 hover:bg-gray-200 cursor-pointer"
                      >
                        {drink.name}
                      </li>
                    ))}
                </ul>
              </div>
              <button
                onClick={() =>
                  setSelectedDrinks(drinks.map((drink) => drink.docId))
                }
                className="mt-2 bg-blue-500 text-white px-2 py-1 rounded"
              >
                Choose All
              </button>
            </div>
            <div className="w-1/2">
              <h3 className="text-lg font-bold mb-2">Selected Drinks</h3>
              <div className="border h-64 overflow-y-scroll">
                <ul>
                  {selectedDrinks.map((drinkDocId) => {
                    const drink = drinks.find(
                      (d) => d.docId === drinkDocId
                    );
                    return (
                      <li
                        key={drinkDocId}
                        onDoubleClick={() => {
                          setSelectedDrinks(
                            selectedDrinks.filter(
                              (id) => id !== drinkDocId
                            )
                          );
                        }}
                        className="p-2 hover:bg-gray-200 cursor-pointer"
                      >
                        {drink ? drink.name : 'Unknown Drink'}
                      </li>
                    );
                  })}
                </ul>
              </div>
              <button
                onClick={() => setSelectedDrinks([])}
                className="mt-2 bg-red-500 text-white px-2 py-1 rounded"
              >
                Remove All
              </button>
            </div>
          </div>
          <div className="flex justify-end mt-4">
            <button
              onClick={() => {
                if (modalType === 'drinksSelection') {
                  // Editing an existing package
                  if (currentPackage) {
                    onPackageChange(
                      currentPackage.docId || '',
                      ['collectionsDrinks'],
                      selectedDrinks
                    );
                  }
                } else {
                  // Setting drinks for the new package
                  updateNewPackageField('collectionsDrinks', selectedDrinks);
                }
                setModalType(null);
                setSelectedDrinks([]);
              }}
              className="bg-green-500 text-white px-4 py-2 rounded mr-2"
            >
              Save
            </button>
            <button
              onClick={() => {
                setModalType(null);
                setSelectedDrinks([]);
              }}
              className="bg-gray-300 px-4 py-2 rounded"
            >
              Cancel
            </button>
          </div>
        </Modal>
      )}

      {/* Packages Editing Modal */}
      {(modalType === 'packagesEditing' ||
        modalType === 'packagesEditingForNewPackage') && (
        <Modal
          isOpen={true}
          onClose={() => {
            setModalType(null);
            setPackagesData([]);
          }}
          title="Edit Packages"
        >
          <div className="space-y-4">
            {packagesData.map((pkgItem, index) => (
              <div key={index} className="flex space-x-2">
                <input
                  type="number"
                  placeholder="Size"
                  value={pkgItem.size ?? ''}
                  onChange={(e) => {
                    const updatedPackages = [...packagesData];
                    updatedPackages[index].size = e.target.valueAsNumber;
                    setPackagesData(updatedPackages);
                  }}
                  className="border p-1 w-full"
                />
                <input
                  type="number"
                  placeholder="Round Up Or Down"
                  value={pkgItem.roundUpOrDown ?? ''}
                  onChange={(e) => {
                    const updatedPackages = [...packagesData];
                    updatedPackages[index].roundUpOrDown =
                      e.target.valueAsNumber;
                    setPackagesData(updatedPackages);
                  }}
                  className="border p-1 w-full"
                />
                <input
                  type="number"
                  placeholder="Discount"
                  value={pkgItem.discount ?? ''}
                  onChange={(e) => {
                    const updatedPackages = [...packagesData];
                    updatedPackages[index].discount = e.target.valueAsNumber;
                    setPackagesData(updatedPackages);
                  }}
                  className="border p-1 w-full"
                />
                <button
                  onClick={() => {
                    const updatedPackages = [...packagesData];
                    updatedPackages.splice(index, 1);
                    setPackagesData(updatedPackages);
                  }}
                  className="bg-red-500 text-white px-2 py-1 rounded"
                >
                  Remove
                </button>
              </div>
            ))}
            <button
              onClick={() => {
                setPackagesData([
                  ...packagesData,
                  { size: 0, roundUpOrDown: 0, discount: 1 },
                ]);
              }}
              className="bg-blue-500 text-white px-4 py-2 rounded"
            >
              Add Package
            </button>
          </div>
          <div className="flex justify-end mt-4">
            <button
              onClick={() => {
                if (modalType === 'packagesEditing') {
                  // Editing existing package
                  if (currentPackage) {
                    onPackageChange(currentPackage.docId || '', ['packages'], packagesData);
                  }
                } else {
                  // Setting packages for the new package
                  updateNewPackageField('packages', packagesData);
                }
                setModalType(null);
                setPackagesData([]);
              }}
              className="bg-green-500 text-white px-4 py-2 rounded mr-2"
            >
              Save
            </button>
            <button
              onClick={() => {
                setModalType(null);
                setPackagesData([]);
              }}
              className="bg-gray-300 px-4 py-2 rounded"
            >
              Cancel
            </button>
          </div>
        </Modal>
      )}
    </div>
  );
};

export default PackagesTable;
